<?php
define('VICTORIOUS_GAME_TYPE_PLAYERDRAFT', 'PLAYERDRAFT');
define('VICTORIOUS_GAME_TYPE_PICKEM', 'PICKEM');
define('VICTORIOUS_GAME_TYPE_ROUNDPICKEM', 'ROUNDPICKEM');
define('VICTORIOUS_GAME_TYPE_BRACKET', 'BRACKET');
define('VICTORIOUS_GAME_TYPE_LIVEDRAFT', 'LIVEDRAFT');
define('VICTORIOUS_GAME_TYPE_PICKSQUARES', 'PICKSQUARES');
define('VICTORIOUS_GAME_TYPE_PICKTIE', 'PICKTIE');
define('VICTORIOUS_GAME_TYPE_GOLFSKIN', 'GOLFSKIN');
define('VICTORIOUS_GAME_TYPE_SURVIVAL', 'SURVIVAL');
define('VICTORIOUS_GAME_TYPE_GOLIATH', 'GOLIATH');
define('VICTORIOUS_GAME_TYPE_MINIGOLIATH', 'MINIGOLIATH');
define('VICTORIOUS_GAME_TYPE_PICKULTIMATE', 'PICKULTIMATE');
define('VICTORIOUS_GAME_TYPE_PICKMONEY', 'PICKMONEY');
define('VICTORIOUS_GAME_TYPE_PICKSPREAD', 'PICKSPREAD');
define('VICTORIOUS_GAME_TYPE_HOWMANYGOALS', 'HOWMANYGOALS');
define('VICTORIOUS_GAME_TYPE_BOTHTEAMSTOSCORE', 'BOTHTEAMSTOSCORE');
define('VICTORIOUS_GAME_TYPE_TEAMDRAFT', 'TEAMDRAFT');
define('VICTORIOUS_GAME_TYPE_BEST5', 'BEST5');
define('VICTORIOUS_GAME_TYPE_SPORTBOOK', 'SPORTBOOK');
define('VICTORIOUS_GAME_TYPE_UPLOADPHOTO', 'UPLOADPHOTO');
define('VICTORIOUS_GAME_TYPE_PORTFOLIO', 'PORTFOLIO');
define('VICTORIOUS_GAME_TYPE_OLDDRAFT', 'OLDDRAFT');
define('VICTORIOUS_GAME_TYPE_NFL_PLAYOFF', 'NFL_PLAYOFF');
define('VICTORIOUS_BALANCE_TYPE_DEFAULT', '');

define('VICTORIOUS_GATEWAY_DFSCOIN', 'DFSCOIN');
define('VICTORIOUS_TABLE_PREFIX', 'vic_');
define('VICTORIOUS_CURRENCY_POS_BEFORE', 'before');
define('VICTORIOUS_CURRENCY_POS_AFTER', 'after');
define('VICTORIOUS_DEFAULT_BALANCE_TYPE_ID', 1);
?>